package com.medical.notification.domain;

public enum NotificationTemplate {
    APPOINTMENT_CONFIRMATION,
    APPOINTMENT_REMINDER,
    APPOINTMENT_CANCELLATION,
    PAYMENT_CONFIRMATION,
    PAYMENT_FAILURE,
    CONSULTATION_REMINDER,
    PASSWORD_RESET,
    ACCOUNT_VERIFICATION
}
